/**
 * Principales ciudades de España (capitales de provincia y grandes municipios).
 * Orden alfabético. Para búsqueda amplia por provincia/radio → fase posterior.
 */
const CIUDADES = [
  "A Coruña",
  "Albacete",
  "Alcalá de Henares",
  "Alcobendas",
  "Alcorcón",
  "Alicante",
  "Almería",
  "Ávila",
  "Badajoz",
  "Badalona",
  "Barcelona",
  "Bilbao",
  "Burgos",
  "Cáceres",
  "Cádiz",
  "Cartagena",
  "Castellón de la Plana",
  "Ceuta",
  "Ciudad Real",
  "Córdoba",
  "Cuenca",
  "Dos Hermanas",
  "Elche",
  "Fuenlabrada",
  "Getafe",
  "Gijón",
  "Girona",
  "Granada",
  "Guadalajara",
  "Hospitalet de Llobregat",
  "Huelva",
  "Huesca",
  "Jaén",
  "Jerez de la Frontera",
  "Las Palmas de Gran Canaria",
  "Leganés",
  "León",
  "Lleida",
  "Logroño",
  "Lugo",
  "Madrid",
  "Málaga",
  "Marbella",
  "Melilla",
  "Móstoles",
  "Murcia",
  "Ourense",
  "Oviedo",
  "Palencia",
  "Palma de Mallorca",
  "Pamplona",
  "Parla",
  "Pontevedra",
  "Reus",
  "Sabadell",
  "Salamanca",
  "San Sebastián",
  "Santander",
  "Santa Cruz de Tenerife",
  "Santiago de Compostela",
  "Segovia",
  "Sevilla",
  "Soria",
  "Tarragona",
  "Terrassa",
  "Teruel",
  "Toledo",
  "Torrejón de Ardoz",
  "Valencia",
  "Valladolid",
  "Vigo",
  "Vitoria-Gasteiz",
  "Zamora",
  "Zaragoza",
] as const;

export type CiudadEspana = {
  value: string;
  label: string;
};

export const CIUDADES_ESPAÑA: CiudadEspana[] = [...CIUDADES]
  .sort((a, b) => a.localeCompare(b, "es", { sensitivity: "base" }))
  .map((nombre) => ({ value: nombre, label: nombre }));
